### ISSUE TITLE
Filter for suffix for tld

### ISSUE THREAD

**Issue by benjohnde** [fgont/ipv6toolkit#48]
```
script6 get-suffix-for-tld au
```

returns

```
com.au
net.au
org.au
edu.au
gov.au
asn.au
id.au
info.au
conf.au
oz.au
act.au
nsw.au
nt.au
qld.au
sa.au
tas.au
vic.au
wa.au
act.edu.au
nsw.edu.au
nt.edu.au
qld.edu.au
sa.edu.au
tas.edu.au
vic.edu.au
wa.edu.au
qld.gov.au
sa.gov.au
tas.gov.au
vic.gov.au
wa.gov.au
```

So I would guess

```
script6 get-suffix-for-tld edu.au
```

should further reduce the list. But that does not work as I expected it.

**Comment by fgont** [comment]
To be honest, for most TLDs there's only a single-level suffix, so I had not even envisioned somebody would try that. But you raise a good point. This could be useful. I will improve this. Thanks

**Comment by fgont** [comment]
Sorry for the delay. I have implemented it!

And you can now also specify a second (optional) numeric parameter that requires a specific number of DNS labels below the specified zone, as in
script6 get-suffix-for-tld gov.au 1

that will print domains like
XXXX.gov.au

but not
XXX.YYYY.gov.au

(since the later has two labels below "gov.au")
